
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 27 13:09:43 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 7;
  public static final int MULTIPLY = 20;
  public static final int IDENT = 28;
  public static final int PLUS = 8;
  public static final int RANGE = 11;
  public static final int RBRACE = 16;
  public static final int RPAREN = 14;
  public static final int CHAR = 29;
  public static final int SEMI = 12;
  public static final int RETURN = 4;
  public static final int LBRACKET = 17;
  public static final int LPAREN = 13;
  public static final int LBRACE = 15;
  public static final int RBRACKET = 18;
  public static final int INC = 23;
  public static final int COMMA = 10;
  public static final int NUMBER = 26;
  public static final int EOF = 0;
  public static final int DIVIDE = 21;
  public static final int PROG = 2;
  public static final int DEC = 24;
  public static final int MINUS = 19;
  public static final int CONST = 6;
  public static final int PRINT = 3;
  public static final int error = 1;
  public static final int ASSIGN = 9;
  public static final int NEW = 5;
  public static final int BOOL = 27;
  public static final int VOID = 25;
  public static final int MODULUS = 22;
}

